version: '3'

networks:
  halvonik-api:

services:
  halvonik-php:
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    image: ppsdocker/halvonik-php
    container_name: HalvonikPhp
    expose:
      - 9000
    networks:
      - halvonik-api
    volumes:
      - ./src:/var/www/html

  halvonik-web:
    image: library/nginx:1.20.1
    container_name: HalvonikWeb
    ports:
      - "8086:80"
    networks:
      - halvonik-api
    depends_on:
      - halvonik-php
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf